# This file created by conda-build 2.1.12
# meta.yaml template originally from:
# /home/weiyan/gcc-7, last modified Sat May 20 06:45:06 2017
# ------------------------------------------------

package:
    name: gcc-7
    version: 7.2.0
source:
    fn: gcc-7.2.0.tar.xz
    md5: ff370482573133a7fcdd96cd2f552292
    # patches:
    #     - 0001-Libiberty-normalize-split-directories.patch
    url: ftp://ftp.gnu.org/gnu/gcc/gcc-7.2.0/gcc-7.2.0.tar.xz
build:
    detect_binary_files_with_prefix: 'false'
    number: 2
    string: '2'
requirements:
    build:
        - mpc 1.1.0 5
        - gmp 6.1.2 0
        - libiconv 1.15
        - mpfr 4.0.1 0
        - isl 0.17.1 1
    run:
        - gmp>=6.1
        - mpfr>=4.0.1
        - mpc>=1.1
        - isl>=0.17,<=0.17.1
        - libiconv>=1.15
test:
    commands:
        - gcc --help
about:
    home: http://gcc.gnu.org/
    license: GPL
    summary: The GNU Compiler Collection
extra:
    final: true
